### PR TITLE
retrieve prNumber from context object

### PR DESCRIPTION
**Pull request by femioladeji**
This PR resolves this issue #3.

The pull request number can be accessed from the context object

### CODE REVIEW

**Review by vitorsavedra — APPROVED** [review]

**Review by hayuna — APPROVED** [review]

**Comment by hayuna** [comment]
Until owner merge this pull request, you can use my fork

hayuna/jest-reporter-action@v0.1.2

**Comment by ziishaned** [comment]
Fixes#3

**Comment by ziishaned** [comment]
resolve #3

**Comment by ziishaned** [comment]
#3

**Pull request merged**
